[build]
builder = "nixpacks"
buildCommand = "npm install && npm run backend:build && npm run frontend:build"

[deploy]
startCommand = "npm run backend:start"
numReplicas = 1
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
